# Generated by Django 5.1.2 on 2024-11-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapril', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=10, unique=True)),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pembayaran', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kembalian', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoapril.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='indoapril.transaksi')),
            ],
        ),
    ]
