# Generated by Django 5.1 on 2024-11-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapril', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=100)),
                ('nama_produk', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
