# Generated by Django 5.1.2 on 2024-11-27 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapril', '0002_produk_transaksi_itemtransaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('stock_lama', models.PositiveIntegerField()),
                ('stock_tambah', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoapril.produk')),
            ],
        ),
    ]
